### ISSUE TITLE
Big birch doors are too transparent

### ISSUE THREAD

**Issue by SigmaFlame** [GeheimagentNr1/ManyIdeasDoors#2]
**Versions**
Minecraft Version: 1.16.5
Minecraft Forge Version: 36.2.35
Mod Version: 1.1.1

**Describe the bug**
Big birch doors are too transparent.

**To Reproduce**
Place two big birch doors in order to make a double big birch door.

**Expected behaviour**
I expect more "glass pixels" to see that the door is closed.

**Screenshots**
Original from your mod : https://i.ibb.co/7VYVY8R/screen.png
A try to fix the problem : https://i.ibb.co/vXFLky6/screen2.png

**Edit:**

I temporary fixed the bug with a ressource pack : [click here to download](https://www.sigmaflame.com/download/SigmaFixes.zip)
I replaced these files with a borderless glass texture :
- assets\manyideas_doors\textures\block\big_doors\wooden\birch\big_door_birch_mid_bottom_right.png
- assets\manyideas_doors\textures\block\big_doors\wooden\birch\big_door_birch_mid_top_right.png

**Comment by Muse31** [comment]
Hello SigmaFlame,

despite, what you think, the texture of the Big Birch Door is not a bug, but a well planned design. I tested about five different glass patterns, and none of them appealed to me as the creator. I hope you will understand my decision, that I will not change the texture of this door. But you found the right solution for your problem: A individual Resource Pack.

Muse

**Comment by SigmaFlame** [comment]
My texture doesn't appeal to you? Maybe the mirror effect?

**Comment by GeheimagentNr1** [comment]
You can build a resource pack to change the textures, models and the blockstates json of the Big Birch Door.
https://minecraft.fandom.com/wiki/Resource_Pack
https://minecraft.fandom.com/wiki/Tutorials/Creating_a_resource_pack
