### ISSUE TITLE
Quark Compatibility

### ISSUE THREAD

**Issue by Dr-WeiAL** [GeheimagentNr1/ManyIdeasDoors#3]
**Versions**
Minecraft Version: 1.18.2
Minecraft Forge Version: 40.1.80
Mod Version: 1.2.0

**Log files**
Please append the log, debug-log and if available the crash-log files.

**Describe the bug**
How to close Double Door Opening, it will conflict with Quark's Double Door Opening

**To Reproduce**
Steps to reproduce the behaviour:
1. Install Quark and Many Ideas Doors
2. Open the double doors

**Expected behaviour**
Is it possible to add a configuration file to disable the Double Door Opening that comes with the mod?

**Screenshots**

**Additional context**
Only for 1x2 doors, larger doors are not affected

**Comment by GeheimagentNr1** [comment]
<table><tbody><tr><th>Status:</th><td>Fixed</td></tr><tr><th>Issue type:</th><td>Bug</td></tr><tr><th>Fix type:</th><td>Bugfix</td></tr><tr><th>Fix version:</th><td>1.2.3</td></tr><tr><th>Fix release date:</th><td>10.04.23</td></tr></tbody></table>

**Issue confirmed for:**

*   Minecraft versions: 1.18.2+

**TODOs:**

*   [x] Fix for Minecraft 1.19+

**Comment by GeheimagentNr1** [comment]
I implemented a fix for the Minecraft versions 1.19, 1.19.1, 1.19.2, 1.19.3 and 1.19.4, because for older versions Quark does not support any way to disabled, its double door feature for specific doors.
