### ISSUE TITLE
[ItemRegistrationIssue]1.18.2 Startup CRASH - SakuraBlossomGrotto/Tumbleweed + Astikor's Carts| NullPointerReferenceExeption

### ISSUE THREAD

**Issue by xFirefalconx** [GeheimagentNr1/ManyIdeasDoors#4]
**Versions**
Minecraft Version: 1.18.2
Minecraft Forge Version: 40.2.0
Mod Version: 1.2.0

**Log files**
Please append the log, debug-log and if available the crash-log files.

[latest.log](https://github.com/GeheimagentNr1/ManyIdeasDoors/files/10663977/latest.log)
[2023-02-06-7.log.gz](https://github.com/GeheimagentNr1/ManyIdeasDoors/files/10663978/2023-02-06-7.log.gz)
[crash-2023-02-06_14.07.02-client.txt](https://github.com/GeheimagentNr1/ManyIdeasDoors/files/10663981/crash-2023-02-06_14.07.02-client.txt)
[crash-2023-02-06_14.11.17-client.txt](https://github.com/GeheimagentNr1/ManyIdeasDoors/files/10663982/crash-2023-02-06_14.11.17-client.txt)
[crash-2023-02-06_13.32.04-client.txt](https://github.com/GeheimagentNr1/ManyIdeasDoors/files/10663983/crash-2023-02-06_13.32.04-client.txt)
[crash-2023-02-06_14.05.21-fml.txt](https://github.com/GeheimagentNr1/ManyIdeasDoors/files/10663985/crash-2023-02-06_14.05.21-fml.txt)
Not all may be relevant but I included them to see the full magnitude. 
Modpack of 190 mods. There MIGHT be EVEN MORE culprits among these as I am still to test 57 mods that potentially can be innocent, though. Please do get in touch with the other authors linked below if you are not a cause but a bystander. 

**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Add following mods: SakuraBlossomGrotto (+ Terra Blender), this also happens with Tumbleweed, add Astikor's Carts. The game will crash when trying to create the pig model due to a NullPointerReferenceExeption. 
Disable either Astikor's Carts or both SakuraBlossomGrotto and Tumbleweed. If either AC, MID + SBG or T are together, the game crashes.

**Expected behaviour**
No crash, lol.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/106652912/216996205-a1be2451-a2dd-40dd-bb90-68744ba4a4d2.png)

**Additional context**

Other crash reports on the other mods
https://github.com/Dekunutter/CherryBlossomGrotto/issues/36 
https://github.com/konwboj/Tumbleweed/issues/33 (no response yet)
https://github.com/GeheimagentNr1/ManyIdeasDoors/issues/4
https://github.com/issork/astikor-carts/issues/88

**Comment by GeheimagentNr1** [comment]
<table><tbody><tr><th>Status:</th><td>Won't fix (cannot be reproduced)</td></tr><tr><th>Issue type:</th><td>None</td></tr><tr><th>Fix type:</th><td>None</td></tr><tr><th>Fix version:</th><td>None</td></tr><tr><th>Fix release date:</th><td>None</td></tr></tbody></table>

**Issue confirmed for:**

*   None

**TODOs:**

*   [x] Test with Minecraft 1.18.2, Forge 42.2.0, AstikoCarts 1.1.2, Cheery Blossom Grotto 0.4.4, TerraBlender Forge 1.2.0.126, Tumbleweed 0.5.4, ManyIdeas Core 1.4.0, ManyIdeas Doors 1.2.0 and Recipes Library 2.0.0

**Comment by GeheimagentNr1** [comment]
With the mentioned mod combination, the issue cannot be reproduced.  
I can launch the game, play and see pigs.

![](https://user-images.githubusercontent.com/20889593/217088655-f62ef46d-22db-43fb-9025-90a572884992.png)

**Comment by xFirefalconx** [comment]
![grafik](https://user-images.githubusercontent.com/106652912/217170467-b4e8ae1d-418c-4f29-a042-09da085e350d.png)
I wonder if this is a hardware issue, now. I created an entirely new modpack and it happens just the same. 
[crash-2023-02-07_06.52.39-client.txt](https://github.com/GeheimagentNr1/ManyIdeasDoors/files/10672355/crash-2023-02-07_06.52.39-client.txt)

**Comment by xFirefalconx** [comment]
Dekunutter found a reson for the crash. It has to do with the way items are registered. Please read the thread and see if you can also implement a fix on your side. https://github.com/Dekunutter/CherryBlossomGrotto/issues/36 In hope you find a way, there is an explanation on what can be done, I am just a noob you might understand it better. 

Tumbleweeds is currently incompatible to ManyIdeasDoors + AstikorCarts combined. Sakurablossomgrotto was incompatible but is now fixed. I hope you can be so kind to apply this to your mod as well so I can activate all mods. 🙏
