### ISSUE TITLE
[1.19.2] Player Sensor

### ISSUE THREAD

**Issue by ZEROX7** [GeheimagentNr1/ManyIdeasDoors#5]
**Versions**
Minecraft Version: [1.19.2]
Minecraft Forge Version: [43.2.8]
Mod Version: [1.2.3]

**Describe the bug**
player sensor aktivated phase turn into random blocks

**Expected behaviour**
it stays as a player sensor

**Screenshots**
![image](https://user-images.githubusercontent.com/12628051/236889704-8c1458b4-ece3-46f4-b354-1bbbafd5896a.png)
![image](https://user-images.githubusercontent.com/12628051/236889822-32780dac-63bd-4d75-a840-f1c0f8637837.png)

**Additional context**
Modpack Singularity Create 1.8.4

**Comment by GeheimagentNr1** [comment]
<table><tbody><tr><th>Status:</th><td>Won't fix (cannot be reproduced)</td></tr><tr><th>Issue type:</th><td>None</td></tr><tr><th>Fix type:</th><td>None</td></tr><tr><th>Fix version:</th><td>None</td></tr><tr><th>Fix release date:</th><td>None</td></tr></tbody></table>

**Issue confirmed for:**

*   None

**TODOs:**

*   [x] Test with Modpack Singularity Create 1.8.4

**Comment by GeheimagentNr1** [comment]
Issue could not be reproduced
https://github.com/GeheimagentNr1/ManyIdeasDoors/assets/20889593/e165eb2f-fe22-497a-8a3d-11ef834ae976
