### ISSUE TITLE
whole pc sound is wayy too loud when placing/breaking a big door

### ISSUE THREAD

**Issue by AlexGuignard** [GeheimagentNr1/ManyIdeasDoors#6]
**Versions**
Minecraft Version:1.19.4
Minecraft Forge Version: 45.0.64
Mod Version: 	ManyIdeasDoors-1.19.4-1.2.3.jar  

no logs specific to sound of this mod 

**Describe the bug**
When placing and breaking a door the sound from the rest of the computer is way too loud fro no reason

**To Reproduce**
4. Place a big door

**Expected behaviour**
no sound bug

**Comment by GeheimagentNr1** [comment]
<table><tbody><tr><th>Status:</th><td><br>Won't fix (cannot be reproduced)</td></tr><tr><th>Issue type:</th><td>None</td></tr><tr><th>Fix type:</th><td>None</td></tr><tr><th>Fix version:</th><td>None</td></tr><tr><th>Fix release date:</th><td>None</td></tr></tbody></table>

**Issue confirmed for:**

*   None

**TODOs:**

*   [x] Test with Minecraft 1.19.4, Forge 45.0.66, Mod Version 1.2.3

**Comment by GeheimagentNr1** [comment]
The mod just uses the default wood and iron place and break sounds from Minecraft.  
Nothing can be changed there.
