### ISSUE TITLE
Breaking big doors quiets whole PC

### ISSUE THREAD

**Issue by Weedoof** [GeheimagentNr1/ManyIdeasDoors#7]
**Versions**
Minecraft Version: 1.19.2
Minecraft Forge Version: 43.2.14
Mod Version: 1.2.3

**Log files**
No relevant info in logs.

**Describe the bug**
As the title. Breaking large doors, such as the big art door, causes the entire PC to go quiet for a moment. Likely related to the large number of blocks breaking at once, as it does not happen if block volume is set to 0 in game settings.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start new world, or open an old one.
2. Start a sound in the background, such as an online tone generator.
3. Place a big door and break it.
4. Observe the temporary quiet

**Expected behaviour**
I expected this not to happen.

**Video demo**
https://github.com/GeheimagentNr1/ManyIdeasDoors/assets/73194383/4cdcf5c9-a84a-4fc5-9567-7360dd30db2a

**Additional context**
Demo was taken in a clean instance containing only Many Ideas Doors, dependencies, and JEI. Issue was also found in a brief test on 1.19.4, on forge version 45.1.0.

┆Issue is synchronized with this [Trello card](https://trello.com/c/4JHuChKn) by [Unito](https://www.unito.io)

**Comment by GeheimagentNr1** [comment]
<table><tbody><tr><th>Status:</th><td>Won't fix</td></tr><tr><th>Issue type:</th><td>Bug</td></tr><tr><th>Fix type:</th><td>None</td></tr><tr><th>Fix version:</th><td>None</td></tr><tr><th>Fix release date:</th><td>None</td></tr></tbody></table>

**TODOs:**

*   [x] Check if the issue can be reproduced
*   [x] Check if the issue can be fixed

**Comment by GeheimagentNr1** [comment]
This is more an "issue" of the Minecraft sound engine or the sound card.  
When I block is broken, the break sound is played.  
For example:  
In case of the Big Art door, the door consists of 3x3x4=36 block. So if the door is broken, Minecraft will play the break sound 36 times.  
I searched for a way to prevent the sound being played 36 times, but there is currently no way, that can be done.
