### ISSUE TITLE
fabric

### ISSUE THREAD

**Issue by hackingrulessodobipeople** [GeheimagentNr1/ManyIdeasDoors#8]
fabric support?

┆Issue is synchronized with this [Trello card](https://trello.com/c/r1V5fl7m) by [Unito](https://www.unito.io)
┆Attachments: <a href="https://github.com/GeheimagentNr1/ManyIdeasDoors/issues/8">ManyIdeasDoors #8 fabric</a>

**Comment by GeheimagentNr1** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [fabric](https://trello.com/c/r1V5fl7m/18-fabric)

**Comment by GeheimagentNr1** [comment]
Currently, there is no time to support multiple very different mod launchers.
