### ISSUE TITLE
Minecraft Version: 1.20.1

### ISSUE THREAD

**Issue by Pixelssssss** [GeheimagentNr1/ManyIdeasDoors#9]
**Versions**
Minecraft Version: 1.20.1
Minecraft Forge Version: 47.1.0
Mod Version: 1.2.3

Copper Corrugated door will not open unless player sensor is used.

1. Grab Copper Corrugated door
2. Place it in a wall or with nothing around it, either way it won't work
4. Nothing else is broken, most doors open and close, game is not lagged, etc.

Copper Corrugated door does not respond to player interaction. *Copper Bar door will also not open, despite the 3x3 doors working. **Just tested more doors, not interested in trying every single door available but the iron glass door and iron dwarf door don't work either. The big ship door works, and the dark oak doors work too. I'm honestly confused by this at this point

![2023-10-16_17 04 55](https://github.com/GeheimagentNr1/ManyIdeasDoors/assets/148162363/95c1f1d1-96f2-47de-80cb-63e7802b2ef6)
![2023-10-16_17 05 04](https://github.com/GeheimagentNr1/ManyIdeasDoors/assets/148162363/f537cf64-e659-4c07-bdd5-55432e3f138b)
![2023-10-16_17 05 07](https://github.com/GeheimagentNr1/ManyIdeasDoors/assets/148162363/b091e68f-0810-4bb5-aae0-8462cf96194c)
![2023-10-16_17 05 09](https://github.com/GeheimagentNr1/ManyIdeasDoors/assets/148162363/67d0dd00-90e9-4aca-ab6a-1f1d72162ab7)

Sorry about the title, just made this account for this bug and messed up when figuring out the UI

**Comment by GeheimagentNr1** [comment]
By default, the **Corrugated** **Door** can be opened by _Redstone_.  
With the [Redstone key](https://secretsoft.de/mods/manyideas-core/core-crafting-and-tools/redstone-key/) of ManyIdeas Core you can change, that the Door can be opened by “_hand only_” or “_both_“.  
  
More Information about the "Corrugated Door":  
https://secretsoft.de/mods/manyideas-doors/doors/metal-doors/corrugated-door/
